-- ─────────────────────────────────────────────────────────────────────────────
-- Reference data that is OURS to define, not copied.
--
-- The legacy schema has no country table: country facts were repeated on every
-- ps_tienda row (name, currency, language) and the rest did not exist at all.
-- iso3 and the tax names below are supplied here; everything else is derived
-- from the distinct countries actually present in ps_tienda.
--
-- GENERATED by azure/Export.java. Re-runnable: rows are matched on iso2.
--
-- price_includes_tax is derived from ps_tienda.impuesto_operacion, which holds
-- '+', '-' or empty rather than a boolean. The meaning is not written down
-- anywhere; it comes from OrdersService::calculateCorrectTotals:
--
--     if ($operacion == '+')  $total = $subtotal + $tax;   // tax added on top
--     else                    $total = $subtotal - $tax;   // tax already in
--
-- So '+' means the stored line amounts EXCLUDE tax, and anything else means
-- they INCLUDE it. Empty falls into the else, so it behaves as '-'. Hence:
--
--     '+'          -> price_includes_tax = 0
--     '-' or empty -> price_includes_tax = 1
--
-- This reproduces what the legacy does today rather than what anyone intended.
-- See README.md for the one case where those may differ (Panama).
-- ─────────────────────────────────────────────────────────────────────────────

-- impuesto_operacion = '+'  ->  price_includes_tax = 0  (total = subtotal + tax)
MERGE dbo.countries AS t USING (SELECT N'AW' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'AW', N'ABW', N'Aruba', N'AWG', N'en', N'BBO', 0);

-- impuesto_operacion = '+'  ->  price_includes_tax = 0  (total = subtotal + tax)
MERGE dbo.countries AS t USING (SELECT N'BB' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'BB', N'BRB', N'Barbados', N'BBD', N'en', N'VAT', 0);

-- impuesto_operacion = '-'  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'CO' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'CO', N'COL', N'Colombia', N'COP', N'es', N'IVA', 1);

-- impuesto_operacion = '-'  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'CR' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'CR', N'CRI', N'Costa Rica', N'CRC', N'es', N'IVA', 1);

-- impuesto_operacion = '-'  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'DO' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'DO', N'DOM', N'Dominican Rep', N'DOP', N'es', N'ITBIS', 1);

-- impuesto_operacion = '-'  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'GT' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'GT', N'GTM', N'Guatemala', N'GTQ', N'es', N'IVA', 1);

-- impuesto_operacion = ''  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'HN' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'HN', N'HND', N'Honduras', N'HNL', N'es', N'ISV', 1);

-- impuesto_operacion = '+'  ->  price_includes_tax = 0  (total = subtotal + tax)
MERGE dbo.countries AS t USING (SELECT N'JM' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'JM', N'JAM', N'Jamaica', N'JMD', N'en', N'GCT', 0);

-- impuesto_operacion = '+'  ->  price_includes_tax = 0  (total = subtotal + tax)
MERGE dbo.countries AS t USING (SELECT N'NI' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'NI', N'NIC', N'Nicaragua', N'NIO', N'es', N'IVA', 0);

-- impuesto_operacion = ''  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'PA' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'PA', N'PAN', N'Panama', N'USD', N'es', N'ITBMS', 1);

-- impuesto_operacion = ''  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'SV' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'SV', N'SLV', N'El Salvador', N'USD', N'es', N'IVA', 1);

-- impuesto_operacion = '-'  ->  price_includes_tax = 1  (total = subtotal - tax)
MERGE dbo.countries AS t USING (SELECT N'TT' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'TT', N'TTO', N'Trinidad', N'TTD', N'en', N'VAT', 1);

-- impuesto_operacion = '+'  ->  price_includes_tax = 0  (total = subtotal + tax)
MERGE dbo.countries AS t USING (SELECT N'VI' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name, price_includes_tax)
     VALUES (N'VI', N'VIR', N'USVI', N'USD', N'en', N'VAT', 0);

GO
