-- ─────────────────────────────────────────────────────────────────────────────
-- Reference data that is OURS to define, not copied.
--
-- The legacy schema has no country table: country facts were repeated on every
-- ps_tienda row (name, currency, language) and the rest did not exist at all.
-- iso3 and the tax names below are supplied here; everything else is derived
-- from the distinct countries actually present in ps_tienda.
--
-- GENERATED by azure/Export.java. Re-runnable: rows are matched on iso2.
--
-- NOT SET: price_includes_tax. The legacy ps_tienda.impuesto_operacion holds
-- '+', '-' or empty rather than a boolean, and its meaning is not documented
-- anywhere in the codebase. It is left at the 0 default. It drives the OMS tax
-- payload, so decide it deliberately before going live rather than inferring it
-- from a sign. The raw legacy value per country is recorded in the comment on
-- each MERGE below.
-- ─────────────────────────────────────────────────────────────────────────────

-- legacy impuesto_operacion = '+'
MERGE dbo.countries AS t USING (SELECT N'AW' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'AW', N'ABW', N'Aruba', N'AWG', N'en', N'BBO');

-- legacy impuesto_operacion = '+'
MERGE dbo.countries AS t USING (SELECT N'BB' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'BB', N'BRB', N'Barbados', N'BBD', N'en', N'VAT');

-- legacy impuesto_operacion = '-'
MERGE dbo.countries AS t USING (SELECT N'CO' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'CO', N'COL', N'Colombia', N'COP', N'es', N'IVA');

-- legacy impuesto_operacion = '-'
MERGE dbo.countries AS t USING (SELECT N'CR' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'CR', N'CRI', N'Costa Rica', N'CRC', N'es', N'IVA');

-- legacy impuesto_operacion = '-'
MERGE dbo.countries AS t USING (SELECT N'DO' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'DO', N'DOM', N'Dominican Rep', N'DOP', N'es', N'ITBIS');

-- legacy impuesto_operacion = '-'
MERGE dbo.countries AS t USING (SELECT N'GT' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'GT', N'GTM', N'Guatemala', N'GTQ', N'es', N'IVA');

-- legacy impuesto_operacion = ''
MERGE dbo.countries AS t USING (SELECT N'HN' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'HN', N'HND', N'Honduras', N'HNL', N'es', N'ISV');

-- legacy impuesto_operacion = '+'
MERGE dbo.countries AS t USING (SELECT N'JM' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'JM', N'JAM', N'Jamaica', N'JMD', N'en', N'GCT');

-- legacy impuesto_operacion = '+'
MERGE dbo.countries AS t USING (SELECT N'NI' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'NI', N'NIC', N'Nicaragua', N'NIO', N'es', N'IVA');

-- legacy impuesto_operacion = ''
MERGE dbo.countries AS t USING (SELECT N'PA' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'PA', N'PAN', N'Panama', N'USD', N'es', N'ITBMS');

-- legacy impuesto_operacion = ''
MERGE dbo.countries AS t USING (SELECT N'SV' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'SV', N'SLV', N'El Salvador', N'USD', N'es', N'IVA');

-- legacy impuesto_operacion = '-'
MERGE dbo.countries AS t USING (SELECT N'TT' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'TT', N'TTO', N'Trinidad', N'TTD', N'en', N'VAT');

-- legacy impuesto_operacion = '+'
MERGE dbo.countries AS t USING (SELECT N'VI' AS iso2) AS s ON t.iso2 = s.iso2
WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)
     VALUES (N'VI', N'VIR', N'USVI', N'USD', N'en', N'VAT');

GO
