import java.sql.*;
import java.io.*;
import java.util.*;

/** Generates the Azure SQL seed + import scripts from the live legacy MySQL database. */
public class Export {
    static Connection c;

    static String q(String s) { return s == null ? "NULL" : "N'" + s.replace("'", "''") + "'"; }
    static String n(Object o) { return o == null ? "NULL" : o.toString(); }

    // ISO3 is not in the legacy schema; it is reference data we define.
    static final Map<String,String> ISO3 = Map.ofEntries(
        Map.entry("AW","ABW"), Map.entry("BB","BRB"), Map.entry("CO","COL"), Map.entry("CR","CRI"),
        Map.entry("DO","DOM"), Map.entry("GT","GTM"), Map.entry("HN","HND"), Map.entry("JM","JAM"),
        Map.entry("NI","NIC"), Map.entry("PA","PAN"), Map.entry("SV","SLV"), Map.entry("TT","TTO"),
        Map.entry("VI","VIR"));
    static final Map<String,String> TAX_NAME = Map.ofEntries(
        Map.entry("CO","IVA"), Map.entry("CR","IVA"), Map.entry("DO","ITBIS"), Map.entry("GT","IVA"),
        Map.entry("HN","ISV"), Map.entry("NI","IVA"), Map.entry("PA","ITBMS"), Map.entry("SV","IVA"),
        Map.entry("AW","BBO"), Map.entry("BB","VAT"), Map.entry("JM","GCT"), Map.entry("TT","VAT"),
        Map.entry("VI","VAT"));

    public static void main(String[] a) throws Exception {
        String url = "jdbc:mysql://" + System.getenv("DB_HOSTNAME") + ":3306/" + System.getenv("DB_DATABASE")
                   + "?useSSL=true&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=CONVERT_TO_NULL";
        c = DriverManager.getConnection(url, System.getenv("DB_USERNAME"), System.getenv("DB_PASSWORD"));
        seed(a[0]);
        imp(a[1]);
        fx(a[2]);
        c.close();
    }

    static void seed(String path) throws Exception {
        PrintWriter w = new PrintWriter(new FileWriter(path));
        w.println("""
            -- ─────────────────────────────────────────────────────────────────────────────
            -- Reference data that is OURS to define, not copied.
            --
            -- The legacy schema has no country table: country facts were repeated on every
            -- ps_tienda row (name, currency, language) and the rest did not exist at all.
            -- iso3 and the tax names below are supplied here; everything else is derived
            -- from the distinct countries actually present in ps_tienda.
            --
            -- GENERATED by azure/Export.java. Re-runnable: rows are matched on iso2.
            --
            -- NOT SET: price_includes_tax. The legacy ps_tienda.impuesto_operacion holds
            -- '+', '-' or empty rather than a boolean, and its meaning is not documented
            -- anywhere in the codebase. It is left at the 0 default. It drives the OMS tax
            -- payload, so decide it deliberately before going live rather than inferring it
            -- from a sign. The raw legacy value per country is recorded in the comment on
            -- each MERGE below.
            -- ─────────────────────────────────────────────────────────────────────────────
            """);
        ResultSet rs = c.createStatement().executeQuery(
            "SELECT pais_iso2, MIN(pais) pais, MIN(moneda) moneda, MIN(idioma) idioma, MIN(impuesto_operacion) imp " +
            "FROM ps_tienda GROUP BY pais_iso2 ORDER BY pais_iso2");
        while (rs.next()) {
            String iso2 = rs.getString(1), imp = rs.getString(5);
            w.printf("-- legacy impuesto_operacion = '%s'%n", imp == null ? "" : imp);
            w.printf("MERGE dbo.countries AS t USING (SELECT %s AS iso2) AS s ON t.iso2 = s.iso2%n", q(iso2));
            w.printf("WHEN NOT MATCHED THEN INSERT (iso2, iso3, name, currency_code, default_language, tax_name)%n");
            w.printf("     VALUES (%s, %s, %s, %s, %s, %s);%n%n",
                q(iso2), q(ISO3.get(iso2)), q(rs.getString(2)), q(rs.getString(3)),
                q(rs.getString(4)), q(TAX_NAME.get(iso2)));
        }
        w.println("GO");
        w.close();
        System.out.println("02_seed.sql generado");
    }

    static void imp(String path) throws Exception {
        PrintWriter w = new PrintWriter(new FileWriter(path));
        w.println("""
            -- ─────────────────────────────────────────────────────────────────────────────
            -- One-time copy of the catalogs out of the legacy MySQL database.
            --
            -- GENERATED by azure/Export.java against the live legacy database. Do not edit
            -- by hand: regenerate. Re-runnable — every statement matches on the natural key
            -- and inserts only what is absent, so a partial run can simply be repeated.
            --
            -- Run AFTER 01_schema.sql and 02_seed.sql.
            --
            -- This is a snapshot. Nothing keeps it in step with the legacy database
            -- afterwards; see README.md.
            -- ─────────────────────────────────────────────────────────────────────────────
            """);

        // clubs
        w.println("-- ── clubs (ex ps_tienda) ─────────────────────────────────────────────────");
        ResultSet rs = c.createStatement().executeQuery(
            "SELECT ps_tienda_id, pais_iso2, nombre, latitud, longitud, status FROM ps_tienda ORDER BY ps_tienda_id");
        int nc = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.clubs AS t USING (SELECT %d AS cn) AS s ON t.club_number = s.cn%n", rs.getInt(1));
            w.printf("WHEN NOT MATCHED THEN INSERT (club_number, country_id, name, latitude, longitude, timezone, is_active)%n");
            w.printf("     VALUES (%d, (SELECT id FROM dbo.countries WHERE iso2 = %s), %s, %s, %s, N'America/Guatemala', %d);%n",
                rs.getInt(1), q(rs.getString(2)), q(rs.getString(3)), n(rs.getObject(4)), n(rs.getObject(5)),
                "A".equals(rs.getString(6)) ? 1 : 0);
            nc++;
        }
        w.println("GO\n");

        // route types
        w.println("-- ── route_types (ex ps_tipos_ruta) ───────────────────────────────────────");
        rs = c.createStatement().executeQuery("SELECT codigo, nombre, descripcion, status FROM ps_tipos_ruta ORDER BY id");
        int nrt = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.route_types AS t USING (SELECT %s AS code) AS s ON t.code = s.code%n", q(rs.getString(1)));
            w.printf("WHEN NOT MATCHED THEN INSERT (code, name, description, is_active) VALUES (%s, %s, %s, %d);%n",
                q(rs.getString(1)), q(rs.getString(2)), q(rs.getString(3)), "A".equals(rs.getString(4)) ? 1 : 0);
            nrt++;
        }
        w.println("GO\n");

        // routes
        w.println("-- ── routes (ex ps_rutas) ─────────────────────────────────────────────────");
        rs = c.createStatement().executeQuery(
            "SELECT r.ps_tienda_id, r.llave, r.descripcion, r.truck_size, r.status, tr.codigo, " +
            "       r.pallet_required, r.halfpallet_required " +
            "FROM ps_rutas r LEFT JOIN ps_tipos_ruta tr ON tr.id = r.tipo_ruta_id ORDER BY r.ps_tienda_id, r.llave");
        int nr = 0;
        while (rs.next()) {
            String rt = rs.getString(6);
            w.printf("MERGE dbo.routes AS t USING (SELECT (SELECT id FROM dbo.clubs WHERE club_number = %d) AS club, %s AS code) AS s%n",
                rs.getInt(1), q(rs.getString(2)));
            w.printf("  ON t.club_id = s.club AND t.code = s.code%n");
            w.printf("WHEN NOT MATCHED AND s.club IS NOT NULL THEN INSERT (club_id, code, route_type_id, name, truck_size, requires_full_pallet, requires_half_pallet, is_active)%n");
            w.printf("     VALUES (s.club, s.code, %s, %s, %s, %d, %d, %d);%n",
                rt == null ? "NULL" : "(SELECT id FROM dbo.route_types WHERE code = " + q(rt) + ")",
                q(rs.getString(3)), n(rs.getObject(4)),
                rs.getInt(7) > 0 ? 1 : 0, rs.getInt(8) > 0 ? 1 : 0,
                "A".equals(rs.getString(5)) ? 1 : 0);
            nr++;
        }
        w.println("GO\n");

        // route prices — one row per tariff column that carried a value
        w.println("""
            -- ── route_prices (ex the tariff columns on ps_rutas) ─────────────────────
            -- The legacy row held a column per tier: pallet_local, halfpallet_local,
            -- `14pallet_local`, `14pallet_usd`. One row per tier here, so adding a tier
            -- stops being an ALTER. A tier the legacy row left NULL produces no row.""");
        rs = c.createStatement().executeQuery(
            "SELECT ps_tienda_id, llave, pallet_local, halfpallet_local, `14pallet_local`, `14pallet_usd` FROM ps_rutas " +
            "ORDER BY ps_tienda_id, llave");
        int np = 0;
        while (rs.next()) {
            int club = rs.getInt(1); String key = rs.getString(2);
            Object[][] tiers = {
                {"FULL_PALLET",    rs.getObject(3), null},
                {"HALF_PALLET",    rs.getObject(4), null},
                {"QUARTER_PALLET", rs.getObject(5), rs.getObject(6)},
            };
            for (Object[] t : tiers) {
                if (t[1] == null && t[2] == null) continue;
                w.printf("MERGE dbo.route_prices AS t USING (SELECT (SELECT r.id FROM dbo.routes r JOIN dbo.clubs cl ON cl.id = r.club_id WHERE cl.club_number = %d AND r.code = %s) AS rid, %s AS ut) AS s%n",
                    club, q(key), q((String) t[0]));
                w.printf("  ON t.route_id = s.rid AND t.unit_type = s.ut%n");
                w.printf("WHEN NOT MATCHED AND s.rid IS NOT NULL THEN INSERT (route_id, unit_type, price_local, price_usd) VALUES (s.rid, s.ut, %s, %s);%n",
                    t[1] == null ? "0" : n(t[1]), t[2] == null ? "0" : n(t[2]));
                np++;
            }
        }
        w.println("GO\n");

        // fiscal document types
        w.println("-- ── fiscal_document_types (ex ps_fel) ────────────────────────────────────");
        rs = c.createStatement().executeQuery(
            "SELECT pais_iso2, nombre_en, nombre_es, formato FROM ps_fel WHERE pais_iso2 IS NOT NULL AND nombre_en IS NOT NULL ORDER BY pais_iso2, felid");
        int nf = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.fiscal_document_types AS t USING (SELECT (SELECT id FROM dbo.countries WHERE iso2 = %s) AS cid, %s AS code) AS s%n",
                q(rs.getString(1)), q(rs.getString(2)));
            w.printf("  ON t.country_id = s.cid AND t.code = s.code%n");
            w.printf("WHEN NOT MATCHED AND s.cid IS NOT NULL THEN INSERT (country_id, code, name_en, name_es, input_mask)%n");
            w.printf("     VALUES (s.cid, s.code, %s, %s, %s);%n",
                q(rs.getString(2)), q(rs.getString(3)), q(rs.getString(4)));
            nf++;
        }
        w.println("GO\n");

        // payment methods
        w.println("""
            -- ── payment methods (ex orders_pago) ─────────────────────────────────────
            -- orders_pago repeated the name on every country row. The concept is defined
            -- once here and the per-country row keeps only the tender key, which genuinely
            -- does vary. The code is derived from the description, upper-cased and
            -- stripped, so two spellings of the same method collapse into one type.""");
        rs = c.createStatement().executeQuery(
            "SELECT DISTINCT UPPER(TRIM(descripcion)) AS code, TRIM(descripcion) AS name FROM orders_pago ORDER BY 1");
        int nmt = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.payment_method_types AS t USING (SELECT %s AS code) AS s ON t.code = s.code%n", q(rs.getString(1)));
            w.printf("WHEN NOT MATCHED THEN INSERT (code, name) VALUES (%s, %s);%n", q(rs.getString(1)), q(rs.getString(2)));
            nmt++;
        }
        w.println("GO\n");
        rs = c.createStatement().executeQuery(
            "SELECT pais_iso2, UPPER(TRIM(descripcion)) AS code, MIN(tender_key) AS tk, MIN(pago_id) AS ord " +
            "FROM orders_pago GROUP BY pais_iso2, UPPER(TRIM(descripcion)) ORDER BY pais_iso2, ord");
        int ncpm = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.country_payment_methods AS t USING (SELECT (SELECT id FROM dbo.countries WHERE iso2 = %s) AS cid, (SELECT id FROM dbo.payment_method_types WHERE code = %s) AS mid) AS s%n",
                q(rs.getString(1)), q(rs.getString(2)));
            w.printf("  ON t.country_id = s.cid AND t.method_type_id = s.mid%n");
            w.printf("WHEN NOT MATCHED AND s.cid IS NOT NULL AND s.mid IS NOT NULL THEN INSERT (country_id, method_type_id, tender_key, sort_order)%n");
            w.printf("     VALUES (s.cid, s.mid, %d, %d);%n", rs.getInt(3), rs.getInt(4));
            ncpm++;
        }
        w.println("GO\n");

        w.close();
        System.out.printf("03_import.sql: %d clubes, %d tipos de ruta, %d rutas, %d tarifas, %d tipos de documento, %d métodos de pago (%d por país)%n",
            nc, nrt, nr, np, nf, nmt, ncpm);
    }

    /**
     * Exchange-rate history, kept out of 03_import.sql on purpose.
     *
     * Quotes snapshot the rate they used, so nothing in the application reads
     * history — only the latest rate per country matters. It is thousands of
     * statements against a handful the app needs, which would bury the rest of
     * the import in review. Optional, and clearly so.
     */
    static void fx(String path) throws Exception {
        PrintWriter w = new PrintWriter(new FileWriter(path));
        w.println("""
            -- ─────────────────────────────────────────────────────────────────────────────
            -- Exchange-rate history (ex ps_tasa_cambio). OPTIONAL.
            --
            -- GENERATED by azure/Export.java. Run after 03_import.sql, or skip it.
            --
            -- Nothing in the application reads this: a quote stores the rate it used, so
            -- history is never consulted to price anything. It is here because throwing
            -- years of rates away is irreversible and keeping them costs only disk.
            --
            -- The legacy table scoped rates per store and every caller ignored that, so the
            -- dimension is dropped: one rate per country per day, most recent row winning
            -- where per-store values disagreed.
            --
            -- If you only want today's rates, run the last statement block per country
            -- instead of the whole file.
            -- ─────────────────────────────────────────────────────────────────────────────
            """);
        ResultSet rs = c.createStatement().executeQuery(
            "SELECT x.ps_pais_iso2, x.d, x.rate FROM (" +
            "  SELECT ps_pais_iso2, DATE(ps_tasa_cambio_fecha) d, ps_tasa_cambio_tipocambio rate," +
            "         ROW_NUMBER() OVER (PARTITION BY ps_pais_iso2, DATE(ps_tasa_cambio_fecha) ORDER BY ps_tasa_cambio_id DESC) rn" +
            "  FROM ps_tasa_cambio WHERE ps_tasa_cambio_tipocambio > 0" +
            ") x WHERE x.rn = 1 ORDER BY x.ps_pais_iso2, x.d");
        int nfx = 0;
        while (rs.next()) {
            w.printf("MERGE dbo.exchange_rates AS t USING (SELECT (SELECT id FROM dbo.countries WHERE iso2 = %s) AS cid, CAST(%s AS DATE) AS d) AS s%n",
                q(rs.getString(1)), q(rs.getString(2)));
            w.printf("  ON t.country_id = s.cid AND t.effective_date = s.d%n");
            w.printf("WHEN NOT MATCHED AND s.cid IS NOT NULL THEN INSERT (country_id, rate, effective_date, source) VALUES (s.cid, %s, s.d, N'legacy ps_tasa_cambio');%n",
                n(rs.getObject(3)));
            nfx++;
        }
        w.println("GO");
        w.close();
        System.out.printf("04_import_fx_history.sql: %d tasas%n", nfx);
    }
}
