import java.sql.*;
import java.io.*;
import java.text.Normalizer;
import java.util.*;

/**
 * Generates QuoteCenter seed + master-data migration SQL from the legacy
 * quotes_dqs_osys_dev database. All FK references in the emitted SQL are
 * resolved via natural-key scalar subqueries, so the output is independent
 * of AUTO_INCREMENT ids in the target database.
 */
public class SeedGen {
    static Connection cn;
    static final Map<String,String> ISO3 = Map.ofEntries(
        Map.entry("GT","GTM"), Map.entry("HN","HND"), Map.entry("SV","SLV"),
        Map.entry("NI","NIC"), Map.entry("CR","CRI"), Map.entry("PA","PAN"),
        Map.entry("CO","COL"), Map.entry("DO","DOM"), Map.entry("TT","TTO"),
        Map.entry("BB","BRB"), Map.entry("AW","ABW"), Map.entry("VI","VIR"),
        Map.entry("JM","JAM"));

    public static void main(String[] args) throws Exception {
        String url = "jdbc:mysql://db-cluster1.cluster-c8zmka2vstwe.us-east-1.rds.amazonaws.com:3306/quotes_dqs_osys_dev?useSSL=true&serverTimezone=America/Guatemala&allowPublicKeyRetrieval=true";
        cn = DriverManager.getConnection(url, "quotes_dqs_osys_dev", "oMroQwDl9zjDIhmQy3gqHI");

        try (PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream("01_seeds_catalogs.sql"), "UTF-8"))) {
            header(w, "Catalog & configuration seeds extracted from legacy quotes_dqs_osys_dev",
                     "Re-run the generator against PROD before the real cutover.");
            countries(w); clubs(w); clubTexts(w); clubDeliverySettings(w);
            clubNotifications(w); geo(w); economicActivities(w); fiscalDocTypes(w);
            paymentMethods(w); quoteTypes(w); cancelReasons(w); omsStatuses(w);
            routeTypes(w); routes(w); exchangeRates(w);
        }
        try (PrintWriter w = new PrintWriter(new OutputStreamWriter(new FileOutputStream("02_migration_master_data.sql"), "UTF-8"))) {
            header(w, "Master-data migration from legacy DQS (members' reusable data)",
                     "Historical transactions (orders/quotations) are NOT migrated — legacy DB stays as read-only archive.");
            memberOverrides(w); memberFiscalProfiles(w);
        }
        System.out.println("done");
    }

    // ── helpers ──────────────────────────────────────────────────────────
    static void header(PrintWriter w, String title, String note) {
        w.println("-- ============================================================================");
        w.println("-- QuoteCenter — " + title);
        w.println("-- Generated by SeedGen from quotes_dqs_osys_dev (DEV data).");
        w.println("-- " + note);
        w.println("-- FKs resolved by natural keys (scalar subqueries) — id-independent.");
        w.println("-- ============================================================================");
        w.println("SET NAMES utf8mb4;");
        w.println();
    }
    static String esc(String s) {
        if (s == null) return "NULL";
        s = s.replace("\\", "\\\\").replace("'", "\\'").replace("\r\n", "\\n").replace("\n", "\\n").replace("\r", "\\n");
        return "'" + s + "'";
    }
    static String n(Object o) { return o == null ? "NULL" : o.toString(); }
    static String code(String name) {
        String x = Normalizer.normalize(name == null ? "" : name, Normalizer.Form.NFD)
            .replaceAll("\\p{M}", "").toUpperCase(Locale.ROOT)
            .replaceAll("[^A-Z0-9]+", "_").replaceAll("^_|_$", "");
        return x.isEmpty() ? "UNKNOWN" : x;
    }
    static String countrySub(String iso2) { return "(SELECT id FROM countries WHERE iso2=" + esc(iso2) + ")"; }
    static String clubSub(int clubNumber) { return "(SELECT id FROM clubs WHERE club_number=" + clubNumber + ")"; }
    static ResultSet q(String sql) throws SQLException { return cn.createStatement().executeQuery(sql); }
    static String bool(Object v) {
        if (v == null) return "0";
        String s = v.toString().trim();
        return (s.equals("0") || s.isEmpty() || s.equalsIgnoreCase("N")) ? "0" : "1";
    }

    // ── 01: catalogs ─────────────────────────────────────────────────────
    static void countries(PrintWriter w) throws SQLException {
        w.println("-- ── countries (legacy countries + dqs_country_information + ps_monto_minimo_cotizacion) ──");
        ResultSet rs = q("SELECT c.code, c.name, c.currency_code, c.currency_symbol, c.currency_name, c.is_active," +
            " ci.uom, m.monto_minimo_usd, m.monto_minimo_local, m.monto_notificacion_transferencia_usd, m.monto_notificacion_transferencia_local" +
            " FROM countries c" +
            " LEFT JOIN (SELECT country_iso, MIN(uom) uom FROM dqs_country_information GROUP BY country_iso) ci ON ci.country_iso=c.code" +
            " LEFT JOIN ps_monto_minimo_cotizacion m ON m.pais_iso2=c.code ORDER BY c.id");
        int k = 0;
        while (rs.next()) {
            String iso2 = rs.getString(1);
            String iso3 = ISO3.getOrDefault(iso2, iso2 + "X");
            w.printf("INSERT INTO countries (iso2, iso3, name, currency_code, currency_symbol, currency_name, weight_unit," +
                " min_quote_amount_usd, min_quote_amount_local, transfer_notice_amount_usd, transfer_notice_amount_local, is_active)%n" +
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);%n",
                esc(iso2), esc(iso3), esc(rs.getString(2)), esc(rs.getString(3)), esc(rs.getString(4)), esc(rs.getString(5)),
                esc(rs.getString(7)),
                rs.getBigDecimal(8) == null ? "50.0000" : rs.getBigDecimal(8).toPlainString(),
                rs.getBigDecimal(9) == null ? "NULL" : rs.getBigDecimal(9).toPlainString(),
                rs.getBigDecimal(10) == null ? "250.0000" : rs.getBigDecimal(10).toPlainString(),
                rs.getBigDecimal(11) == null ? "NULL" : rs.getBigDecimal(11).toPlainString(),
                rs.getInt(6));
            k++;
        }
        w.println("-- countries: " + k + " rows\n");
    }

    static void clubs(PrintWriter w) throws SQLException {
        w.println("-- ── clubs (ex ps_tienda identity/location columns) ──");
        ResultSet rs = q("SELECT ps_tienda_id, nombre, pais_iso2, direccion, telefono, latitud, longitud, nit, zonahoraria, status FROM ps_tienda ORDER BY ps_tienda_id");
        int k = 0;
        while (rs.next()) {
            String tz = rs.getString(9);
            if (tz == null || tz.isBlank()) tz = "America/Guatemala";
            w.printf("INSERT INTO clubs (club_number, country_id, name, address, phone, latitude, longitude, tax_registration_number, timezone, is_active)%n" +
                "VALUES (%d, %s, %s, %s, %s, %s, %s, %s, %s, %s);%n",
                rs.getInt(1), countrySub(rs.getString(3)), esc(rs.getString(2)), esc(rs.getString(4)), esc(rs.getString(5)),
                n(rs.getObject(6)), n(rs.getObject(7)), esc(rs.getString(8)), esc(tz),
                "A".equalsIgnoreCase(rs.getString(10)) ? "1" : "0");
            k++;
        }
        w.println("-- clubs: " + k + " rows\n");
    }

    static void clubTexts(PrintWriter w) throws SQLException {
        w.println("-- ── club_texts (ex 8 inline text columns on ps_tienda) ──");
        String[][] map = {
            {"titulo_cotizacion",     "QUOTE_TITLE"},
            {"disclaimer",            "QUOTE_DISCLAIMER"},
            {"disclaimer1",           "QUOTE_DISCLAIMER_2"},
            {"titulo_delivery",       "DELIVERY_TITLE"},
            {"delivery_disclaimer",   "DELIVERY_DISCLAIMER"},
            {"titulo_delivery_ddc",   "DDC_DELIVERY_TITLE"},
            {"delivery_disclaimer_dcc","DDC_DELIVERY_DISCLAIMER"},
            {"hd_contrato",           "HOME_DELIVERY_CONTRACT"}};
        int k = 0;
        for (String[] m : map) {
            ResultSet rs = q("SELECT ps_tienda_id, `" + m[0] + "` FROM ps_tienda WHERE TRIM(COALESCE(`" + m[0] + "`,'')) <> '' ORDER BY ps_tienda_id");
            while (rs.next()) {
                w.printf("INSERT INTO club_texts (club_id, text_type, content) VALUES (%s, '%s', %s);%n",
                    clubSub(rs.getInt(1)), m[1], esc(rs.getString(2)));
                k++;
            }
        }
        w.println("-- club_texts: " + k + " rows\n");
    }

    static void clubDeliverySettings(PrintWriter w) throws SQLException {
        w.println("-- ── club_delivery_settings (ex ps_tienda delivery flag cluster) ──");
        ResultSet rs = q("SELECT ps_tienda_id, delivery, delivery_ddc, ddc_inventory, hd_contrato_option, verzonas, delivery_opdescripcion FROM ps_tienda ORDER BY ps_tienda_id");
        int k = 0;
        while (rs.next()) {
            w.printf("INSERT INTO club_delivery_settings (club_id, home_delivery_enabled, ddc_delivery_enabled, ddc_inventory_enabled, home_delivery_contract_required, show_zones, show_option_descriptions)%n" +
                "VALUES (%s, %s, %s, %s, %s, %s, %s);%n",
                clubSub(rs.getInt(1)), bool(rs.getObject(2)), bool(rs.getObject(3)), bool(rs.getObject(4)),
                bool(rs.getObject(5)), bool(rs.getObject(6)), bool(rs.getObject(7)));
            k++;
        }
        w.println("-- club_delivery_settings: " + k + " rows\n");
    }

    // delivery_op1..op4 NOT migrated: no consumer in the new stack, meaning undocumented.

    static void clubNotifications(PrintWriter w) throws SQLException {
        w.println("-- ── club_notification_recipients (ex comma-list ps_tienda.notificaciones) ──");
        ResultSet rs = q("SELECT ps_tienda_id, notificaciones FROM ps_tienda WHERE TRIM(COALESCE(notificaciones,'')) <> ''");
        int k = 0;
        while (rs.next()) {
            Set<String> seen = new LinkedHashSet<>();
            for (String e : rs.getString(2).split("[,;\\s]+")) {
                e = e.trim();
                if (!e.isEmpty() && e.contains("@") && seen.add(e.toLowerCase(Locale.ROOT))) {
                    w.printf("INSERT INTO club_notification_recipients (club_id, email) VALUES (%s, %s);%n", clubSub(rs.getInt(1)), esc(e));
                    k++;
                }
            }
        }
        w.println("-- club_notification_recipients: " + k + " rows\n");
    }

    // GlobalPay credentials NOT migrated: every club uses PriceSmart Payments (2026-08-10).

    static void geo(PrintWriter w) throws SQLException {
        w.println("-- ── cities / zones / neighborhoods (FEL geo chain, string codes → FK chain) ──");
        int k = 0;
        ResultSet rs = q("SELECT country, code, name FROM cities ORDER BY country, code");
        while (rs.next()) {
            w.printf("INSERT INTO cities (country_id, code, name) VALUES (%s, %s, %s);%n",
                countrySub(rs.getString(1)), esc(rs.getString(2)), esc(rs.getString(3)));
            k++;
        }
        w.println("-- cities: " + k + " rows");
        k = 0;
        // legacy zones lack a country column; resolve city ambiguity via the cities catalog country
        rs = q("SELECT z.code, z.name, z.city_code, c.country FROM zones z JOIN cities c ON c.code=z.city_code ORDER BY c.country, z.city_code, z.code");
        while (rs.next()) {
            w.printf("INSERT INTO zones (city_id, code, name) VALUES ((SELECT ci.id FROM cities ci JOIN countries co ON ci.country_id=co.id WHERE ci.code=%s AND co.iso2=%s), %s, %s);%n",
                esc(rs.getString(3)), esc(rs.getString(4)), esc(rs.getString(1)), esc(rs.getString(2)));
            k++;
        }
        w.println("-- zones: " + k + " rows");
        k = 0;
        rs = q("SELECT n.code, n.name, n.zone_code, n.city_code, c.country FROM neighborhoods n JOIN cities c ON c.code=n.city_code ORDER BY c.country, n.city_code, n.zone_code, n.code");
        while (rs.next()) {
            w.printf("INSERT INTO neighborhoods (zone_id, code, name) VALUES ((SELECT z.id FROM zones z JOIN cities ci ON z.city_id=ci.id JOIN countries co ON ci.country_id=co.id WHERE z.code=%s AND ci.code=%s AND co.iso2=%s), %s, %s);%n",
                esc(rs.getString(3)), esc(rs.getString(4)), esc(rs.getString(5)), esc(rs.getString(1)), esc(rs.getString(2)));
            k++;
        }
        w.println("-- neighborhoods: " + k + " rows\n");
    }

    static void economicActivities(PrintWriter w) throws SQLException {
        w.println("-- ── economic_activities ──");
        ResultSet rs = q("SELECT country, code, value FROM economic_activities ORDER BY country, code");
        int k = 0;
        while (rs.next()) {
            w.printf("INSERT INTO economic_activities (country_id, code, name) VALUES (%s, %s, %s);%n",
                countrySub(rs.getString(1)), esc(rs.getString(2)), esc(rs.getString(3)));
            k++;
        }
        w.println("-- economic_activities: " + k + " rows\n");
    }

    static Map<Integer,String[]> felMap = new LinkedHashMap<>(); // felid -> [iso2, code]

    static void fiscalDocTypes(PrintWriter w) throws SQLException {
        w.println("-- ── fiscal_document_types (ex ps_fel; stable code derived from name_en, deduped per country) ──");
        ResultSet rs = q("SELECT felid, pais_iso2, nombre_en, nombre_es, minimo, maximo, formato, formato2 FROM ps_fel WHERE pais_iso2 IS NOT NULL ORDER BY pais_iso2, felid");
        Map<String,Integer> used = new HashMap<>();
        int k = 0;
        while (rs.next()) {
            String iso2 = rs.getString(2);
            String base = code(rs.getString(3) != null ? rs.getString(3) : rs.getString(4));
            String key = iso2 + ":" + base;
            int c = used.merge(key, 1, Integer::sum);
            String cd = c == 1 ? base : base + "_" + c;
            felMap.put(rs.getInt(1), new String[]{iso2, cd});
            w.printf("INSERT INTO fiscal_document_types (country_id, code, name_en, name_es, min_length, max_length, input_mask, validation_regex)%n" +
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s);%n",
                countrySub(iso2), esc(cd), esc(rs.getString(3)), esc(rs.getString(4)),
                n(rs.getObject(5)), n(rs.getObject(6)), esc(rs.getString(7)), esc(rs.getString(8)));
            k++;
        }
        w.println("-- fiscal_document_types: " + k + " rows (felid→code mapping preserved for profile migration)\n");
    }

    static void paymentMethods(PrintWriter w) throws SQLException {
        w.println("-- ── payment_method_types + country_payment_methods (ex orders_pago) ──");
        w.println("-- Method concept defined once; per-country row carries availability + tender_key.");
        ResultSet rs = q("SELECT pais_iso2, descripcion, tender_key FROM orders_pago ORDER BY pago_id");
        // pass 1: distinct method names → type catalog with derived codes
        Map<String,String> typeCode = new LinkedHashMap<>(); // name -> code
        List<String[]> rows = new ArrayList<>();
        while (rs.next()) rows.add(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
        Map<String,Integer> usedCodes = new HashMap<>();
        for (String[] r : rows) {
            if (typeCode.containsKey(r[1])) continue;
            String base = code(r[1]);
            int c = usedCodes.merge(base, 1, Integer::sum);
            typeCode.put(r[1], c == 1 ? base : base + "_" + c);
        }
        for (Map.Entry<String,String> e : typeCode.entrySet())
            w.printf("INSERT INTO payment_method_types (code, name) VALUES (%s, %s);%n", esc(e.getValue()), esc(e.getKey()));
        w.println("-- payment_method_types: " + typeCode.size() + " rows");
        // pass 2: per-country availability, dedup on (country, method)
        int k = 0;
        Set<String> dedup = new HashSet<>();
        for (String[] r : rows) {
            if (!dedup.add(r[0] + "|" + r[1])) continue;
            w.printf("INSERT INTO country_payment_methods (country_id, method_type_id, tender_key, sort_order)" +
                " VALUES (%s, (SELECT id FROM payment_method_types WHERE code=%s), %s, %d);%n",
                countrySub(r[0]), esc(typeCode.get(r[1])), r[2], k);
            k++;
        }
        w.println("-- country_payment_methods: " + k + " rows\n");
    }

    static void quoteTypes(PrintWriter w) throws SQLException {
        w.println("-- ── quote_types (ex orders_type) ──");
        ResultSet rs = q("SELECT otid, description FROM orders_type ORDER BY otid");
        int k = 0;
        while (rs.next()) {
            w.printf("INSERT INTO quote_types (code, name) VALUES (%s, %s);%n", esc(code(rs.getString(2))), esc(rs.getString(2)));
            k++;
        }
        w.println("-- quote_types: " + k + " rows\n");
    }

    static void cancelReasons(PrintWriter w) throws SQLException {
        w.println("-- ── quotation_cancel_reasons ──");
        ResultSet rs = q("SELECT id, description FROM quotation_cancel_reasons ORDER BY id");
        int k = 0;
        while (rs.next()) {
            w.printf("INSERT INTO quotation_cancel_reasons (description, sort_order) VALUES (%s, %d);%n", esc(rs.getString(2)), rs.getInt(1));
            k++;
        }
        w.println("-- quotation_cancel_reasons: " + k + " rows\n");
    }

    static void omsStatuses(PrintWriter w) throws SQLException {
        w.println("-- ── oms_statuses (ex orders_oms_status; display translations only) ──");
        ResultSet rs = q("SELECT omsid, name_eng, name_esp FROM orders_oms_status ORDER BY omsid");
        int k = 0;
        while (rs.next()) {
            w.printf("INSERT INTO oms_statuses (code, name_en, name_es) VALUES (%s, %s, %s);%n",
                esc(rs.getString(1)), esc(rs.getString(2)), esc(rs.getString(3)));
            k++;
        }
        w.println("-- oms_statuses: " + k + " rows\n");
    }

    static Map<Integer,String> routeTypeCodes = new HashMap<>();

    static void routeTypes(PrintWriter w) throws SQLException {
        w.println("-- ── route_types (ex ps_tipos_ruta) ──");
        ResultSet rs = q("SELECT id, codigo, nombre, descripcion, status FROM ps_tipos_ruta ORDER BY id");
        int k = 0;
        while (rs.next()) {
            routeTypeCodes.put(rs.getInt(1), rs.getString(2));
            w.printf("INSERT INTO route_types (code, name, description, is_active) VALUES (%s, %s, %s, %s);%n",
                esc(rs.getString(2)), esc(rs.getString(3)), esc(rs.getString(4)), "A".equalsIgnoreCase(rs.getString(5)) ? "1" : "0");
            k++;
        }
        w.println("-- route_types: " + k + " rows\n");
    }

    static void routes(PrintWriter w) throws SQLException {
        w.println("-- ── routes + route_prices (ex ps_rutas; repeating price group unpivoted) ──");
        ResultSet rs = q("SELECT r.ps_tienda_id, r.llave, r.tipo_ruta_id, r.descripcion, r.truck_size, r.status," +
            " r.pallet_required, r.halfpallet_required, r.cost_local, r.cost_usd, r.pallet_local, r.pallet_usd," +
            " r.halfpallet_local, r.halfpallet_usd, r.`14pallet_local`, r.`14pallet_usd`" +
            " FROM ps_rutas r JOIN ps_tienda t ON t.ps_tienda_id=r.ps_tienda_id ORDER BY r.ps_tienda_id, r.llave");
        int k = 0, p = 0;
        while (rs.next()) {
            int club = rs.getInt(1);
            String rcode = rs.getString(2);
            Integer rt = (Integer) rs.getObject(3);
            String rtSub = rt == null || !routeTypeCodes.containsKey(rt) ? "NULL"
                : "(SELECT id FROM route_types WHERE code=" + esc(routeTypeCodes.get(rt)) + ")";
            w.printf("INSERT INTO routes (club_id, code, route_type_id, name, truck_size, requires_full_pallet, requires_half_pallet, is_active)%n" +
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s);%n",
                clubSub(club), esc(rcode), rtSub, esc(rs.getString(4)), n(rs.getObject(5)),
                bool(rs.getObject(7)), bool(rs.getObject(8)), "A".equalsIgnoreCase(rs.getString(6)) ? "1" : "0");
            k++;
            String routeSub = "(SELECT r2.id FROM routes r2 JOIN clubs c2 ON r2.club_id=c2.id WHERE c2.club_number=" + club + " AND r2.code=" + esc(rcode) + ")";
            String[][] units = {{"TRIP","9","10"},{"FULL_PALLET","11","12"},{"HALF_PALLET","13","14"},{"QUARTER_PALLET","15","16"}};
            for (String[] u : units) {
                double local = rs.getDouble(Integer.parseInt(u[1]));
                double usd   = rs.getDouble(Integer.parseInt(u[2]));
                if (local == 0 && usd == 0 && !u[0].equals("TRIP")) continue;
                w.printf("INSERT INTO route_prices (route_id, unit_type, price_local, price_usd) VALUES (%s, '%s', %.4f, %.4f);%n",
                    routeSub, u[0], local, usd);
                p++;
            }
        }
        w.println("-- routes: " + k + " rows; route_prices: " + p + " rows\n");
    }

    static void exchangeRates(PrintWriter w) throws SQLException {
        w.println("-- ── exchange_rates (latest rate per country from ps_tasa_cambio; full history stays archived) ──");
        ResultSet rs = q("SELECT t.ps_pais_iso2, t.ps_tasa_cambio_tipocambio, DATE(t.ps_tasa_cambio_fecha)" +
            " FROM ps_tasa_cambio t JOIN (SELECT ps_pais_iso2 p, MAX(ps_tasa_cambio_fecha) f FROM ps_tasa_cambio GROUP BY ps_pais_iso2) m" +
            " ON m.p=t.ps_pais_iso2 AND m.f=t.ps_tasa_cambio_fecha" +
            " JOIN countries c ON c.code=t.ps_pais_iso2 GROUP BY t.ps_pais_iso2, t.ps_tasa_cambio_tipocambio, DATE(t.ps_tasa_cambio_fecha)");
        int k = 0;
        Set<String> seen = new HashSet<>();
        while (rs.next()) {
            if (!seen.add(rs.getString(1))) continue;
            w.printf("INSERT INTO exchange_rates (country_id, rate, effective_date, source) VALUES (%s, %.6f, '%s', 'migrated: latest ps_tasa_cambio');%n",
                countrySub(rs.getString(1)), rs.getDouble(2), rs.getString(3));
            k++;
        }
        w.println("-- exchange_rates: " + k + " rows\n");
    }

    // ── 02: master data ──────────────────────────────────────────────────
    static void memberOverrides(PrintWriter w) throws SQLException {
        w.println("-- ── member_contact_overrides (ex ps_socios — the 4 columns the code actually reads) ──");
        ResultSet rs = q("SELECT membership, email, cellPhone, addressLine1, businessName FROM ps_socios ORDER BY membership");
        int k = 0;
        Set<String> seen = new HashSet<>();
        while (rs.next()) {
            String m = rs.getString(1);
            if (m == null || m.isBlank() || !seen.add(m)) continue;
            w.printf("INSERT INTO member_contact_overrides (membership_number, email, phone, address_line1, business_name) VALUES (%s, %s, %s, %s, %s);%n",
                esc(m), esc(blank(rs.getString(2))), esc(blank(rs.getString(3))), esc(blank(rs.getString(4))), esc(blank(rs.getString(5))));
            k++;
        }
        w.println("-- member_contact_overrides: " + k + " rows\n");
    }
    static String blank(String s) { return s == null || s.isBlank() ? null : s.trim(); }

    static void memberFiscalProfiles(PrintWriter w) throws SQLException {
        w.println("-- ── member_fiscal_profiles (ex ps_socios_fel distinct membership+document, most complete row wins) ──");
        // fel country fallback via felMap built from ps_fel
        felMap.isEmpty();
        ResultSet frs = q("SELECT felid, pais_iso2, nombre_en, nombre_es FROM ps_fel WHERE pais_iso2 IS NOT NULL ORDER BY pais_iso2, felid");
        if (felMap.isEmpty()) { // populate when 01-generation didn't run in this process
            Map<String,Integer> used = new HashMap<>();
            while (frs.next()) {
                String iso2 = frs.getString(2);
                String base = code(frs.getString(3) != null ? frs.getString(3) : frs.getString(4));
                int c = used.merge(iso2 + ":" + base, 1, Integer::sum);
                felMap.put(frs.getInt(1), new String[]{iso2, c == 1 ? base : base + "_" + c});
            }
        }
        // country resolution cascade: explicit country → ps_fel via felid →
        // store of the quote (cotizacion→orders→ps_tienda) → member master (ps_socios.countryCode)
        ResultSet rs = q("SELECT f.membership, f.nit, f.businessname, f.address, f.phone, f.email, f.felid, f.nit_validated," +
            " f.city_code, f.zone_code, f.neighborhood_code, f.nrc, f.economic_activity_code," +
            " COALESCE(f.country, t.pais_iso2, s.countryCode) AS country, f.tax_invoice, f.tiquete_electronico" +
            " FROM ps_socios_fel f" +
            " LEFT JOIN orders o ON o.id=f.cotizacion" +
            " LEFT JOIN ps_tienda t ON t.ps_tienda_id=o.store_id" +
            " LEFT JOIN ps_socios s ON s.membership=f.membership" +
            " ORDER BY f.membership, f.nit, f.cotizacion IS NULL DESC");
        Map<String,String[]> best = new LinkedHashMap<>();
        int skippedNoCountry = 0, skippedBadCountry = 0, skippedNoDoc = 0;
        while (rs.next()) {
            String[] r = new String[16];
            for (int i = 0; i < 16; i++) r[i] = rs.getString(i + 1);
            if (r[0] == null || r[1] == null || r[1].isBlank()) { skippedNoDoc++; continue; }
            String iso2 = blank(r[13]);
            if (iso2 == null && r[6] != null && felMap.containsKey(Integer.parseInt(r[6]))) iso2 = felMap.get(Integer.parseInt(r[6]))[0];
            if (iso2 == null) { skippedNoCountry++; continue; }
            if (iso2.length() > 2) iso2 = iso2.substring(0, 2); // 'CRC' style values
            if (!ISO3.containsKey(iso2)) { skippedBadCountry++; continue; } // VE/IL/CH/CB junk in member master
            r[13] = iso2;
            String key = r[0] + "|" + iso2 + "|" + r[1];
            String[] prev = best.get(key);
            if (prev == null || filled(r) > filled(prev)) best.put(key, r);
        }
        w.println("-- skipped: " + skippedNoDoc + " rows without document number, " + skippedNoCountry +
                  " with unresolvable country, " + skippedBadCountry + " with countries outside the catalog (VE/IL/CH/CB…)");
        int k = 0;
        for (String[] r : best.values()) {
            String docTypeSub = "NULL";
            if (r[6] != null && felMap.containsKey(Integer.parseInt(r[6]))) {
                String[] fm = felMap.get(Integer.parseInt(r[6]));
                docTypeSub = "(SELECT f.id FROM fiscal_document_types f JOIN countries c ON f.country_id=c.id WHERE c.iso2=" + esc(fm[0]) + " AND f.code=" + esc(fm[1]) + ")";
            }
            String iso2 = r[13];
            String citySub = blank(r[8]) == null ? "NULL"
                : "(SELECT ci.id FROM cities ci JOIN countries co ON ci.country_id=co.id WHERE ci.code=" + esc(r[8]) + " AND co.iso2=" + esc(iso2) + ")";
            String zoneSub = blank(r[9]) == null || blank(r[8]) == null ? "NULL"
                : "(SELECT z.id FROM zones z JOIN cities ci ON z.city_id=ci.id JOIN countries co ON ci.country_id=co.id WHERE z.code=" + esc(r[9]) + " AND ci.code=" + esc(r[8]) + " AND co.iso2=" + esc(iso2) + ")";
            String nbSub = blank(r[10]) == null || blank(r[9]) == null || blank(r[8]) == null ? "NULL"
                : "(SELECT n.id FROM neighborhoods n JOIN zones z ON n.zone_id=z.id JOIN cities ci ON z.city_id=ci.id JOIN countries co ON ci.country_id=co.id WHERE n.code=" + esc(r[10]) + " AND z.code=" + esc(r[9]) + " AND ci.code=" + esc(r[8]) + " AND co.iso2=" + esc(iso2) + ")";
            String eaSub = blank(r[12]) == null ? "NULL"
                : "(SELECT ea.id FROM economic_activities ea JOIN countries co ON ea.country_id=co.id WHERE ea.code=" + esc(r[12]) + " AND co.iso2=" + esc(iso2) + ")";
            w.printf("INSERT INTO member_fiscal_profiles (membership_number, country_id, document_type_id, document_number, document_validated," +
                " business_name, address, phone, email, nrc, economic_activity_id, city_id, zone_id, neighborhood_id, wants_tax_invoice, wants_electronic_ticket)%n" +
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);%n",
                esc(r[0]), countrySub(iso2), docTypeSub, esc(r[1]), bool(r[7]),
                esc(r[2] == null ? "" : r[2]), esc(blank(r[3])), esc(blank(r[4])), esc(blank(r[5])), esc(blank(r[11])),
                eaSub, citySub, zoneSub, nbSub, bool(r[14]), bool(r[15]));
            k++;
        }
        w.println("-- member_fiscal_profiles: " + k + " unique profiles\n");
    }
    static int filled(String[] r) { int c = 0; for (String s : r) if (s != null && !s.isBlank()) c++; return c; }
}
